inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - ./rubocop-cops/sidekiq_dont_use_keyword_arguments.rb

# Add Rubocop rules we want to override below, sort them alphabetically

AssignmentInCondition: { Enabled: true, AllowSafeAssignment: false } # `if foo = bar` <- BAD
Layout/LineLength: { Enabled: true, Severity: warning, AutoCorrect: false } # lower severity, disable autocorrect
Layout/EmptyLineAfterGuardClause: { Enabled: true, Severity: warning, AutoCorrect: false }
Naming/InclusiveLanguage: { Enabled: false } # disable
Naming/PredicateName: { Enabled: false } # disable, need to migrate our DB columns to use this one
Style/DateTime: { Enabled: false } # disable
Style/MethodCallWithArgsParentheses: { Enabled: false } # disable
Style/OpenStructUse: { Enabled: false } # disable
Style/StringLiterals: { Enabled: true, EnforcedStyle: single_quotes } # use single_quotes
Style/StringLiteralsInInterpolation: { Enabled: true, EnforcedStyle: single_quotes } # use single_quotes
Style/TrailingCommaInArguments: { Enabled: true, EnforcedStyleForMultiline: consistent_comma } # enable
Style/TrailingCommaInBlockArgs: { Enabled: true } # enable
Style/WordArray: { Enabled: false } # disable
Style/BlockDelimiters: { Enabled: true } # {...} for single-line blocks and do..end for multi-line blocks
